### PR TITLE
Benedict

### PR DESCRIPTION
**Pull request by BenedictBen**
Created an alert component for conditional rendering when a user clicks on the heart button.

### CODE REVIEW

**Review by arkhurst — CHANGES_REQUESTED** [review]
you having linting & type errors

**Review by arkhurst — COMMENTED** [review]
also, can you add screenshots of what you worked on & URL to the task?

**Review by BenedictBen — COMMENTED** [review]
URL: http://172.20.112.1:3000

**Review by arkhurst — COMMENTED** [review]
@BenedictBen did you take a picture with your phone?

**Comment by BenedictBen** [comment]
> @BenedictBen did you take a picture with your phone?

Yes I did I was having a minor issue with my laptop screenshot. I will add a new one if this is not acceptable.

**Pull request closed without merging**
