### PR TITLE
feat: [API] Edit Content Details

### PR DESCRIPTION
**Pull request by Bendomey**
## PR Name or Description

feat: Edit Content Details

## Overview

Register an endpoint to update contents on FE

## Detailed Technical Change

- Endpoint: `PATCH /api/v1/contents/{contentId}`
- Body: 
```
{
  title?: string
  visibility?: "PUBLIC" | "PRIVATE"
  amount?: number
}
```
- Authorisation: Needs Token
> You should only pass the keys you really want to update. Don't pass all the values to improve the efficiency of that endpoint because each key has some checks done on them before the update is successfully completed

## Testing Approach & Result

- Login
- Create a content
- Call the edit endpoint to update any detail
- Verify by looking at the response  from the api call or by calling the get endpoint(`GET /api/v1/content/{contentId}`) with the same content Id

## Related Work

N/A

## Documentation

N/A

### CODE REVIEW

**Review by arkhurst — COMMENTED** [review]
@Zunuoh , i believe endpoints are ready for the UI work

**Review by arkhurst — APPROVED** [review]

**Comment by Zunuoh** [comment]
Noted

**Comment by Zunuoh** [comment]
Whats the base url?

**Comment by Bendomey** [comment]
> Whats the base url?

I think that should already be available in our functions(`fetchClient`).

**Comment by Zunuoh** [comment]
Okay

**Pull request merged**
