### PR TITLE
feat: Auth

### PR DESCRIPTION
**Pull request by Bendomey**
- [x] Click on login to continue with oauth2
- [x] Add express server
- [x] Google Login
- [x] Facebook Login
- [x] Twitter Login
- [x] Create endpoint `/authenticate`
- [x] Integrate `/authenticate` on frontend
- [x] Handle session
- [x] Onboarding

### CODE REVIEW

**Comment by Bendomey** [comment]
## Mobile Onboarding View
Screenshot 2024-01-02 at 19 04 39

**Comment by Bendomey** [comment]
## Desktop Onboarding View

**Comment by Bendomey** [comment]
Screenshot 2024-01-02 at 21 03 07

**Comment by Bendomey** [comment]
Screenshot 2024-01-02 at 22 21 29

**Review by arkhurst — APPROVED** [review]

**Pull request merged**
