### PR TITLE
feat: Related Images for a Content

### PR DESCRIPTION
**Pull request by Bendomey**
## PR Name or Description

Related Images for a Content

## Overview

User should be able to see related images when they view a single image content

## Detailed Technical Change

- "The definition of image relation": Contents that have similar tags.

## Testing Approach & Result

Select an image. If we have contents with similar tags, they should appear beneath it.

## Related Work

N/A

## Documentation

N/A

### CODE REVIEW

**Review by arkhurst — APPROVED** [review]
🚀 Easy !
Quick question though, the formatting for the frontend code looks off or it's just me?

**Comment by arkhurst** [comment]
> > 🚀 Easy ! Quick question though, the formatting for the frontend code looks off or it's just me?
> 
> Screenshot 2024-12-19 at 2 53 43 PM
> You mean this?

Yup, that's correct

**Comment by Bendomey** [comment]
> > > 🚀 Easy ! Quick question though, the formatting for the frontend code looks off or it's just me?
> > 
> > 
> > Screenshot 2024-12-19 at 2 53 43 PM
> > You mean this?
> 
> Yup, that's correct

Ah, I think it's just github (It probably wraps it and does not overflow for a scroll feature - I think there might be a setting for this on your account to make it not wrap. I could be wrong.) This is local:
Screenshot 2024-12-19 at 2 57 09 PM

**Comment by arkhurst** [comment]
> > > > 🚀 Easy ! Quick question though, the formatting for the frontend code looks off or it's just me?
> > > 
> > > 
> > > Screenshot 2024-12-19 at 2 53 43 PM
> > > You mean this?
> > 
> > 
> > Yup, that's correct
> 
> Ah, I think it's just github (It probably wraps it and does not overflow for a scroll feature - I think there might be a setting for this on your account to make it not wrap. I could be wrong.) This is local: Screenshot 2024-12-19 at 2 57 09 PM

No worri4es, was just curious!

**Pull request merged**
